### ISSUE TITLE
Axion may 2017 starting problem

### ISSUE THREAD

**Issue by volmike** [daly/axiom#8]
Hi!
When starting gitcloned  axiom  may 2017 ver I get:
**clef trying to get the initial terminal settings: Inappropriate ioctl for device
fork_Axiom: Failed to reopen server: No such file or directory**
with exit.

**Comment by daly** [comment]
I don't have enough information to debug this. What operating system? clef is a command-line
editor that runs in front of Axiom. You may not need it. Try
   axiom -noclef

**Comment by volmike** [comment]
Hi
It's Linux Mint 17.3 Cinnamon 64-bit.
If I run axiom as
**#!/bin/sh
cd ~/axiom
export AXIOM=`pwd`/mnt/mint
export PATH=$AXIOM/bin:$PATH
axiom -noclef**
it returns:
**fork_Axiom: Failed to reopen server: No such file or directory**

**Comment by daly** [comment]
Is this built with the latest sources? There is a known issue with Linux that was recently fixed.

I will build a machine with Mint 17.3 to see if I can reproduce the problem.

**Comment by daly** [comment]
Well, THAT was a surprise. The default install of Mint 17.3 does not include <stdio.h>.
And the texlive installation does not include pstricks.

wget http://axiom-developer.org/axiom-website/downloads/axiom-ubuntu64-may2017-bin.tgz
tar -zxf axiom-ubuntu64-may2017-bin.tgz
cd axiom
export AXIOM=`pwd`/mnt/ubuntu
export PATH=$AXIOM/bin:$PATH
axiom

works for me.

**Comment by volmike** [comment]
That's OK. But what if I want to compile Axiom from github source?
I had no problems with it till Mon 7/3.
Today's make doesn't  have any fatal errors but I still get the same error.

**Comment by daly** [comment]
Are you able to build from source on Mint 17.3? I use Mint 12 Lisa on my local master so Mint has been a main platform for years. If I read what you wrote correctly you were able to build Axiom from source prior to 7/3. Does the following work:

git clone git://github.com/daly/axiom
cd axiom
git reset --hard r0ecd7ae
export AXIOM=`pwd`/mnt/ubuntu
export PATH=$AXIOM/bin:$PATH
make


I built a new machine with Mint 17.3 yesterday. By default it did not contain the tools needed to build Axiom, such as <stdio.h>. The texlive version in the Mint apt-get does not contain pstricks. I spent 4 hours last night downloading a DVD of the texlive distro. Now I have to figure out how to install it. I'm taking notes on what I need to do to get Mint 17.3 to compile Axiom.  If I succeed I will post the necessary steps.

As you can see from the download website I maintained Axiom's build process on many different platforms. Before 2007 the community insisted on a fresh build every 2 months. Building (and debugging) on that set of platforms takes a week or more of time due to things like the above issues. That only leaves 7 out of 8 weeks for everything else like debugging, documenting, refactoring, rewriting, and research.

Clearly Axiom can run on Mint 17.3. It just won't compile there. If you can figure out why or how, please post the results here or on the axiom-developer.org developer mailing list. 

I'm under intense pressure to show some research results as CMU has been generous enough to bring me on as a Visiting Scholar. I am trying to push Axiom into new territory so maintenance tasks are getting less of my time. Any help you can provide to debug the Mint build problem would be greatly appreciated.

**Comment by volmike** [comment]
Well, I just made an update to Mint 18 Sarah and the problem still appears.
The only thing I can provide for you is the the make log.
[axiomlog.zip](https://github.com/daly/axiom/files/1134144/axiomlog.zip)
